logging.level.root = WARN
debug=true

# PostgreSQL Datasource Configuration
spring.datasource.url = jdbc:postgresql://localhost:5432/hospital
spring.datasource.username = postgres
spring.datasource.password = root

# Hibernate and JPA
spring.thymeleaf.cache=false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = create
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
